services:
  web:
    image: python:3.14.0a3-alpine3.21
    ports:
      - "5000:5000"
    environment:
      - GYM_SECRET_KEY=${GYM_SECRET_KEY}
    volumes:
      - ${DATABASE_LOCATION}:/GymApp/app
    command: sh -c "
      apk update
      && apk upgrade
      && apk add git
      && if [ ! -d ./GymApp ]; then git clone https://github.com/MelecaZane/GymApp.git; fi
      && cd ./GymApp
      && pip install -r ./requirements.txt
      && apk add sqlite
      && sudo apt instal -y sqlite3
      && gunicorn -b 0.0.0.0:5000 app:flask_app
      "
      