"""empty message

Revision ID: fd90bb4e3817
Revises: cce034f2f6b1
Create Date: 2025-01-02 16:29:16.030829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd90bb4e3817'
down_revision = 'cce034f2f6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_exercise_muscle_group', 'muscle_group', ['muscle_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercise_muscle_group', type_='foreignkey')
        batch_op.drop_column('muscle_group_id')

    # ### end Alembic commands ###
